### ISSUE TITLE
[Bug] Minified Memberlist Not Working

### ISSUE THREAD

**Issue by Kederan** [Chloe-ko/Discord-Stuff#2]
**Which plugin is this about?**
Minified Memberlist

**Describe the Bug**
The member list is not hidden by default. And when I put the mouse over the member list it does not do anything.

**To Reproduce**
I turned the plugin off and on. Reloaded my client and still get the same bug.

**Expected Behavior**
Hide the member list by default. When I hover my mouse over the left side of my client the member lists pops out.

**Screenshots**
![2019-09-13_20-28-23](https://user-images.githubusercontent.com/19885815/64901293-a3396780-d665-11e9-88f9-2a2c2eed7613.gif)

**Discord Version**
Stable

**Comment by Chloe-ko** [comment]
Hey, I'm sorry for this late reply, I never bothered to check this Git repo, that's on me.
I just uploaded a commit, and while that commit doesn't make a lot of changes, i just want to be sure.
Does the code, as it is in the repo right now, still not work for you?

**Comment by Chloe-ko** [comment]
As another user confirmed the current code should work, I will see this issue as closed for now. If you still have issues, feel free to contact me again, this time I'll be responsive.

**Comment by bogyjemm** [comment]
a year later same issue
