### ISSUE TITLE
Box height relies on elements inside container.

### ISSUE THREAD

**Issue by L-m-b** [Chloe-ko/Discord-Stuff#3]
I assume its not intentional to have the members list appear short in direct group chats (not full window height, and instead relying on the contents for size, as mentioned in title)
Note: this is only in direct message group chats, in case you miss that
![image](https://user-images.githubusercontent.com/30617839/72419201-7098aa80-37d0-11ea-879c-d6ccf215fe30.png)

**Comment by Chloe-ko** [comment]
Hello, sorry for the late reply. This has been fixed in the most recent update. #
