### ISSUE TITLE
Broken with new discord UI changes

### ISSUE THREAD

**Issue by dexman545** [Chloe-ko/Discord-Stuff#4]
New UI changes have offset the minified version

![image](https://user-images.githubusercontent.com/4873274/73710742-db078100-46d2-11ea-9fbc-362cfcd34a44.png)
![image](https://user-images.githubusercontent.com/4873274/73710750-e0fd6200-46d2-11ea-8225-16a76ef4a7fd.png)

**Comment by dexman545** [comment]
A patch I made that fixes it (mostly)
`.da-membersWrap:hover .da-scrollerWrap {
	transform: translateX(-280px);
	background: rgba(0, 0, 0, .2);
}`

**Comment by Chloe-ko** [comment]
Thanks for the info and sorry for the late reply, this has been fixed in the most recent update.
